name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
     matrix:
      node-version: [17.x]

    steps:
      - uses: actions/checkout@v4

      - name: initial modules
        run: npm install
      - name: build server project
        run: npm run build

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
