name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
     matrix:
      project: [server, client]

    steps:
      - uses: actions/checkout@v4
      - name: setup node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: initial modules
        run: npm install
        working-directory: server
      - name: build server
        run: npm run build
        working-directory: server

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
